name = "Stream Kit"
description = "Retrieves game info for streaming tools"
author = "jimmybaxter"
version = "1.0"
api_version = 10
dst_compatible = true
all_clients_require_mod = false
client_only_mod = true
icon_atlas = "modicon.xml"
icon = "modicon.tex"
server_filter_tags = {}
forumthread = ""
configuration_options = {}
